version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu

deploy:
  - destination: /var/www/html/wsr-arjit
    source: /
    branch: main
    phase: BeforeInstall

  - destination: /var/www/html/wsr-arjit-uni
    source: /
    branch: upload
    phase: BeforeInstall



