version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wsr-arjit
    when:
        branch: "main"
  - source: /
    destination: /var/www/html/wsr-arjit-uni
    when:
        branch: "upload"

hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit
      when:
        branch: "main"
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit-uni
      when:
        branch: "upload"
