version: 0.0
os: linux



# For the "main" branch
main:
  files:
    - source: /
      destination: /var/www/html/wsr-arjit
      pattern: "**"

  hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit

# For the "upload" branch
upload:
  files:
    - source: /
      destination: /var/www/html/wsr-arjit-uni
      pattern: "**"
 
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit-uni
