version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wsr-arjit-uni
  - source: /
    destination: /var/www/html/wsr-arjit-uni
appspec:
  - overwrite: true
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit-uni
      when:
        branch: "main"
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
      destination: /var/www/html/wsr-arjit-uni
      when:
        branch: "upload"


