version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wsr-arjit
    pattern: "**"
    overwrite: true
    permissions:
      - object: "*"
        owner: "www-data"
        group: "www-data"
        mode: "755"
  - source: /
    destination: /var/www/html/wsr-arjit-uni
    pattern: "**"
    overwrite: true
    permissions:
      - object: "*"
        owner: "www-data"
        group: "www-data"
        mode: "755"

hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu

