version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: scripts/application-wsr.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu

deploy:
  - destination: /var/www/html/wsr-arjit
    source: /var/www/html/main
    phase: BeforeInstall
    conditions:
      - !Equals [ "refs/heads/main", "{CODEDEPLOY_REPO}", true ]

  - destination: /var/www/html/wsr-arjit-uni
    source: /var/www/html/upload
    phase: BeforeInstall
    conditions:
      - !Equals [ "refs/heads/dev", "{CODEDEPLOY_REPO}", true ]



