version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      #- npm install

  build:
    commands:
      #- npm run build

  post_build:
    commands:
      # Sync the build artifacts to S3 bucket
      #- aws s3 sync build/ s3://${BUCKET_NAME}

      # Add your custom shell script execution
      - chmod +x build.sh
      - ./build.sh

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
